version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Dependencias
          command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - run:
          name: Test
          command: invoke test
